version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: submission_db
      POSTGRES_USER: submission
      POSTGRES_PASSWORD: submission
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=submission_db
      - POSTGRES_USER=submission
      - POSTGRES_PASSWORD=submission
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://host.docker.internal:8000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data:
