# Generated by Django 6.0.6 on 2026-06-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audits_audi_applica_c3d8be_idx',
            old_name='audits_audi_applica_idx',
        ),
    ]
